name: build
on:
  push:
    tags: ["*"]

env:
  ECR_REPO: 305587085711.dkr.ecr.us-west-2.amazonaws.com/twitter-scraper

jobs:
  build_image:
    name: Build docker image
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 305587085711.dkr.ecr.us-west-2.amazonaws.com
          username: ${{ secrets.ECR_ACCESS_KEY_ID }}
          password: ${{ secrets.ECR_ACCESS_KEY }}

      - name: Prepare environment variables
        run: |
          echo "HOME=$HOME" | tee -a $GITHUB_ENV
          echo "BUILDX_BUILDER=${{ steps.docker-builder.outputs.name }}" | tee -a $GITHUB_ENV
          echo "BUILDX_BUILDER_CONTAINER=buildx_buildkit_${{ steps.docker-builder.outputs.name }}0" | tee -a $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::7}" | tee -a $GITHUB_ENV
          GIT_TAG=$(git tag --points-at HEAD)
          echo "GIT_TAG=$GIT_TAG" | tee -a $GITHUB_ENV
          GIT_BRANCH=$(git branch --show-current)
          echo "GIT_BRANCH=$GIT_BRANCH" | tee -a $GITHUB_ENV
          echo "REF_NAME=$(echo ${GIT_TAG:-$GITHUB_REF_NAME} | sed 's/[^a-zA-Z0-9._]/-/g')" | tee -a $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.ECR_REPO }}
          tags: |
            type=ref,event=branch
            type=ref,event=branch,suffix=-${{ github.run_number }}
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=sha,format=short,prefix=
            type=raw,value=${{ env.REF_NAME }},enable=${{ github.event_name == 'pull_request' }}
            type=raw,value=${{ env.GIT_BRANCH }},enable=${{ env.GIT_BRANCH != '' }}
            type=raw,value=latest,enable=${{ env.GIT_BRANCH == 'alt-main' }}

      - name: Build with cache and push images
        uses: docker/build-push-action@v3
        id: docker_build
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.docker-builder.outputs.name }}
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: |
            type=registry,ref=${{ env.ECR_REPO }}:latest
          tags: ${{ steps.meta.outputs.tags }}